import { getVercelOidcToken } from '@vercel/oidc';

const LAT=42.5944, LON=-114.4008;
const DOWNSTREAM_SITE='13090500';
const MILNER_SITE='13088000';
const UA='ShoshoneFallsLive/1.0 (chrisizworski.com)';
const TIME_ZONE='America/Boise';
const FETCH_TIMEOUT_MS=3800;
const MAX_USGS_AGE_MIN=120;
const HARNESS_TIMEOUT_MS=4200;
const HARNESS_URL=process.env.HARNESS_URL||'https://agentbase-registry-izworski-gmailcoms-projects.vercel.app/api/harness';

const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
async function fetchJson(url,options={},timeout=FETCH_TIMEOUT_MS){const c=new AbortController();const t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{...options,signal:c.signal});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return await r.json()}finally{clearTimeout(t)}}

function ageMinutes(iso){const t=Date.parse(iso||'');return Number.isFinite(t)?Math.max(0,(Date.now()-t)/60000):null}
function localParts(date=new Date()){const parts=new Intl.DateTimeFormat('en-US',{timeZone:TIME_ZONE,hour:'2-digit',minute:'2-digit',hourCycle:'h23',weekday:'short',month:'2-digit',day:'2-digit'}).formatToParts(date);return Object.fromEntries(parts.map(p=>[p.type,p.value]))}
function parseUsgs(payload){const series=payload?.value?.timeSeries||[];const discharge=series.find(x=>x?.variable?.variableCode?.[0]?.value==='00060');const values=(discharge?.values?.[0]?.value||[]).map(v=>({cfs:num(v.value),time:v.dateTime})).filter(v=>Number.isFinite(v.cfs)&&Date.parse(v.time));if(!values.length)return{cfs:null,observedAt:null,ageMinutes:null,trend6:null,trend24:null};const latest=values.at(-1);const nearestAgo=hours=>{const target=Date.parse(latest.time)-hours*3600000;return values.reduce((best,v)=>Math.abs(Date.parse(v.time)-target)<Math.abs(Date.parse(best.time)-target)?v:best,values[0])};const v6=nearestAgo(6),v24=nearestAgo(24);const pct=(old)=>old?.cfs?((latest.cfs-old.cfs)/old.cfs)*100:null;return{cfs:latest.cfs,observedAt:latest.time,ageMinutes:ageMinutes(latest.time),trend6:pct(v6),trend24:pct(v24),series:values.slice(-96)}}
function trendLabel(pct){if(!Number.isFinite(pct))return'Trend unavailable';if(pct>=20)return`Rising fast · +${Math.round(pct)}% / 24h`;if(pct>=6)return`Rising · +${Math.round(pct)}% / 24h`;if(pct<=-20)return`Falling fast · ${Math.round(pct)}% / 24h`;if(pct<=-6)return`Falling · ${Math.round(pct)}% / 24h`;return'Fairly steady / 24h'}
async function getUsgs(site){const url=`https://waterservices.usgs.gov/nwis/iv/?format=json&sites=${site}&parameterCd=00060&period=P2D&siteStatus=all`;const payload=await fetchJson(url,{headers:{'User-Agent':UA}});return{...parseUsgs(payload),url,site}}
function wind(text){const xs=[...String(text||'').matchAll(/(\d+)/g)].map(m=>Number(m[1])).filter(Number.isFinite);return xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null}
async function getNws(){const headers={'User-Agent':UA,Accept:'application/geo+json, application/json'};const point=await fetchJson(`https://api.weather.gov/points/${LAT},${LON}`,{headers});const hourlyUrl=point?.properties?.forecastHourly;const [hourly,alerts]=await Promise.all([fetchJson(hourlyUrl,{headers}),fetchJson(`https://api.weather.gov/alerts/active?point=${LAT},${LON}`,{headers})]);const periods=(hourly?.properties?.periods||[]).slice(0,36);return{periods:periods.map(p=>({time:p.startTime,tempF:num(p.temperature),windMph:wind(p.windSpeed),summary:p.shortForecast||null,precipChance:num(p?.probabilityOfPrecipitation?.value)})),alerts:(alerts?.features||[]).map(a=>({event:a?.properties?.event,severity:a?.properties?.severity,headline:a?.properties?.headline})),urls:{hourlyUrl,alerts:`https://api.weather.gov/alerts/active?point=${LAT},${LON}`}}}
async function getOpenMeteo(){const url=`https://api.open-meteo.com/v1/forecast?latitude=${LAT}&longitude=${LON}&current=temperature_2m,apparent_temperature,cloud_cover,wind_speed_10m&hourly=temperature_2m,cloud_cover,precipitation_probability,wind_speed_10m&daily=sunrise,sunset&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=America%2FBoise&forecast_days=3`;const p=await fetchJson(url);const hs=(p?.hourly?.time||[]).map((time,i)=>({time,tempF:num(p.hourly.temperature_2m?.[i]),cloud:num(p.hourly.cloud_cover?.[i]),precipChance:num(p.hourly.precipitation_probability?.[i]),windMph:num(p.hourly.wind_speed_10m?.[i])}));return{current:{tempF:num(p?.current?.temperature_2m),feelsF:num(p?.current?.apparent_temperature),cloud:num(p?.current?.cloud_cover),windMph:num(p?.current?.wind_speed_10m)},hours:hs,daylight:(p?.daily?.time||[]).map((date,i)=>({date,sunrise:p.daily.sunrise?.[i]||null,sunset:p.daily.sunset?.[i]||null})),url}}
function accessState(){const p=localParts();const h=Number(p.hour),min=Number(p.minute);const mins=h*60+min;const open=mins>=420&&mins<1260;return{openNow:open,note:'Current City notice sets gate hours at 7 AM–9 PM; verify official notices before a long drive.',basis:'Twin Falls temporary gate-hours notice dated June 16, 2026',source:'https://www.tfid.org/m/newsflash/home/detail/1687'}}
function weatherSummary(nws,om){const n=nws?.periods?.[0]||{};return{tempF:Number.isFinite(n.tempF)?n.tempF:om?.current?.tempF,windMph:Number.isFinite(n.windMph)?n.windMph:om?.current?.windMph,summary:n.summary||'Current weather',cloud:om?.current?.cloud,precipChance:n.precipChance}}
function daylightContains(time,daylight){const t=Date.parse(time);return(daylight||[]).some(d=>t>=Date.parse(d.sunrise)&&t<=Date.parse(d.sunset))}
function candidateWindows(nws,om,access){const now=Date.now();const hours=(om?.hours||[]).filter(h=>{const t=Date.parse(h.time);return t>=now-3600000&&t<=now+36*3600000&&daylightContains(h.time,om.daylight)});const grouped=[];for(let i=0;i<hours.length;i+=2){const slice=hours.slice(i,i+2);if(!slice.length)continue;const avg=k=>{const xs=slice.map(x=>x[k]).filter(Number.isFinite);return xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null};const start=slice[0].time,end=slice.at(-1).time;const score=100-(avg('cloud')??50)*.45-(avg('precipChance')??0)*.22-Math.max(0,(avg('windMph')??0)-15)*1.2;grouped.push({id:`w${i}`,start,end,label:`${new Intl.DateTimeFormat('en-US',{timeZone:TIME_ZONE,weekday:'short',hour:'numeric'}).format(new Date(start))}–${new Intl.DateTimeFormat('en-US',{timeZone:TIME_ZONE,hour:'numeric'}).format(new Date(end))}`,cloud:avg('cloud'),precipChance:avg('precipChance'),windMph:avg('windMph'),weatherScore:Math.round(clamp(score)),accessLikely:true})}return grouped.sort((a,b)=>b.weatherScore-a.weatherScore).slice(0,5)}
function riverSignal(down,milner){const freshDown=Number.isFinite(down.cfs)&&down.ageMinutes<=MAX_USGS_AGE_MIN;const freshMilner=Number.isFinite(milner.cfs)&&milner.ageMinutes<=MAX_USGS_AGE_MIN;let strength='unknown';let score=40;if(freshDown){if(down.cfs>=7000){strength='very strong river context';score=92}else if(down.cfs>=3000){strength='strong river context';score=80}else if(down.cfs>=1200){strength='moderate river context';score=65}else if(down.cfs>=500){strength='low-to-moderate river context';score=52}else{strength='low river context';score=38}}if(freshMilner&&Number.isFinite(milner.trend24))score+=clamp(milner.trend24,-15,15)*.4;return{strength,score:Math.round(clamp(score)),freshDown,freshMilner}}
function deterministicDecision(travel,down,milner,weather,access,alerts=[]){const sig=riverSignal(down,milner);const severe=(alerts||[]).some(a=>/Tornado|Severe Thunderstorm|Flash Flood|High Wind Warning|Dust Storm|Extreme Heat/i.test(a.event||''));if(severe)return{state:'warn',headline:'Check hazards before going',explanation:'A current NWS hazard affects the area. Scenic conditions do not override an official weather hazard.',confidenceLabel:'High',reasonCode:'hazard'};if(!access.openNow)return{state:'warn',headline:'Park gate is closed right now',explanation:'Plan the next daylight/open window. The official live camera can still tell you what the falls look like before you leave.',confidenceLabel:'High',reasonCode:'closed'};
 const highSignal=sig.score>=78;const rising=Number.isFinite(milner.trend24)&&milner.trend24>12;
 if(highSignal&&rising&&travel!=='special')return{state:'go',headline:'Promising river signal — verify the falls on camera',explanation:'Upstream and downstream river context is strong/rising, but exact waterfall spill is not directly verified. If you are already nearby, this is a reasonable time to check the overlook.',confidenceLabel:'Medium',reasonCode:'promising'};
 const copy={nearby:['Worth a quick look if you are already nearby','Exact waterfall discharge is not directly verified. Check the official live camera; if the view is weak, Dierkes Lake keeps the stop useful.'],under1:['Check the live camera before you detour','The river context is useful, but it cannot prove how much water is spilling over Shoshone Falls. A quick camera check should decide the detour.'],one2:['Verify the falls before a 1–2 hour drive','The tool will not turn a downstream river gauge into a waterfall-flow claim. Use the live camera before committing the drive.'],special:['Not enough evidence for a dedicated-trip recommendation','A special trip deserves a verified waterfall-flow signal. Until Idaho Power’s Shoshone dataset semantics are confirmed, use the official camera and announced release information before leaving.']}[travel]||['Check the official camera','Exact waterfall spill is not directly verified.'];return{state:travel==='nearby'?'unknown':'warn',headline:copy[0],explanation:copy[1],confidenceLabel:'Medium',reasonCode:'unverified_direct_flow'}}
async function harnessToken(){if(process.env.HARNESS_ACCESS_KEY)return process.env.HARNESS_ACCESS_KEY;if(process.env.VERCEL_OIDC_TOKEN)return process.env.VERCEL_OIDC_TOKEN;try{return String(await getVercelOidcToken()||'')}catch{return''}}
async function rankWindowWithJev(windows,context){if(!windows.length)return null;const token=await harnessToken();if(!token)return null;const options=Object.fromEntries(windows.map(w=>[w.id,`start=${w.start}; end=${w.end}; weather_score=${w.weatherScore}; cloud=${w.cloud??'unknown'}; precip_chance=${w.precipChance??'unknown'}; wind_mph=${w.windMph??'unknown'}`]));const payload={action:'decide',task:'Choose the best practical daylight viewing window for a visitor to Shoshone Falls using only the supplied candidate windows. This ranking is about weather, daylight and practicality; it must not imply or invent waterfall flow.',options,context,constraints:['Choose only a supplied id or NONE.','Do not invent waterfall discharge or a release.','Lower cloud/precipitation and reasonable wind can improve scenic/photo conditions.','Prefer a sooner good window over a slightly better much-later window.','This is not a safety guarantee.']};const c=new AbortController();const timer=setTimeout(()=>c.abort(),HARNESS_TIMEOUT_MS);try{const r=await fetch(HARNESS_URL,{method:'POST',signal:c.signal,redirect:'error',headers:{authorization:`Bearer ${token}`,'content-type':'application/json',accept:'application/json'},body:JSON.stringify(payload)});if(!r.ok)return null;const j=await r.json();const choice=j?.result?.choice?.choice,conf=num(j?.result?.choice?.confidence),inj=num(j?.result?.injection_dependency);if(!windows.some(w=>w.id===choice)||!Number.isFinite(conf)||conf<.52||(Number.isFinite(inj)&&inj>=.45))return null;return{choiceId:choice,confidence:conf,mode:'shared-harness-jev'}}catch{return null}finally{clearTimeout(timer)}}
function bestWindow(windows,jev){const chosen=jev?windows.find(w=>w.id===jev.choiceId):windows[0];if(!chosen)return null;return{...chosen,why:`${jev?'JEV ranked':'Deterministic ranking from'} daylight/weather candidates only. This does not predict waterfall flow.`}}

export default async function handler(req,res){if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});const travel=['nearby','under1','one2','special'].includes(req.query?.travel)?req.query.travel:'nearby';const health={downstream:false,milner:false,nws:false,openMeteo:false};const errors={};const results=await Promise.allSettled([getUsgs(DOWNSTREAM_SITE),getUsgs(MILNER_SITE),getNws(),getOpenMeteo()]);let downstream={},milner={},nws={periods:[],alerts:[]},om={current:{},hours:[],daylight:[]};for(const [i,r] of results.entries()){if(r.status==='fulfilled'){if(i===0){downstream=r.value;health.downstream=true}if(i===1){milner=r.value;health.milner=true}if(i===2){nws=r.value;health.nws=true}if(i===3){om=r.value;health.openMeteo=true}}else errors[['downstream','milner','nws','openMeteo'][i]]=String(r.reason?.message||r.reason)}if(Number.isFinite(downstream.ageMinutes)&&downstream.ageMinutes>MAX_USGS_AGE_MIN)health.downstream=false;if(Number.isFinite(milner.ageMinutes)&&milner.ageMinutes>MAX_USGS_AGE_MIN)health.milner=false;downstream.trend24Label=trendLabel(downstream.trend24);milner.trend24Label=trendLabel(milner.trend24);const access=accessState();const weather=weatherSummary(nws,om);const decision=deterministicDecision(travel,downstream,milner,weather,access,nws.alerts);const windows=candidateWindows(nws,om,access);const jev=await rankWindowWithJev(windows,{travel,current_time:new Date().toISOString(),direct_waterfall_flow_verified:false,downstream_cfs:downstream.cfs??null,milner_cfs:milner.cfs??null,decision_reason:decision.reasonCode});decision.bestWindow=bestWindow(windows,jev);res.setHeader('Cache-Control','public, s-maxage=300, stale-while-revalidate=900');res.setHeader('X-Robots-Tag','noindex, nofollow');res.status(200).json({generatedAt:new Date().toISOString(),travel,waterfall:{directVerified:false,cfs:null,observedAt:null,ageMinutes:null,semanticStatus:'Idaho Power publicly exposes a Shoshone Falls Discharge Hydrograph, but this release does not equate that field with waterfall spill until the dataset definition is verified.',officialCamera:'https://www.youtube.com/watch?v=PS0N6ZlbiqQ'},downstream:{...downstream,role:'Snake River downstream context; not waterfall spill'},milner:{...milner,role:'Upstream Snake River / Milner context'},weather,alerts:nws.alerts,access,decision,jev:jev?{mode:jev.mode,confidence:jev.confidence}:null,sourceHealth:health,sourceErrors:errors,sources:{city:'https://www.tfid.org/309/Shoshone-Falls',idahoPower:'https://idastream.idahopower.com/',usgsDownstream:`https://waterdata.usgs.gov/monitoring-location/${DOWNSTREAM_SITE}/`,usgsMilner:`https://waterdata.usgs.gov/monitoring-location/${MILNER_SITE}/`,nws:'https://www.weather.gov/'}})}
